### ISSUE TITLE
Specify contract of the Updater

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/FundraisingStore#13]
As per comment on #11

**Comment by WMDE-Fisch** [comment]
I was thinking about the updater again and depending on what it should do it might not be necessary.

There is already the possibility to update a DB to a schema by running the corresponding doctrine cli command.

e,g, on the front or backend just go to 
``cd vendor/bin/`` 
and run 
``php doctrine orm:schema-tool:update``

**Comment by JeroenDeDauw** [comment]
Is `php doctrine orm:schema-tool:update` always sufficient though? What if data needs to be migrated from some old to a new table? Or is this something we will never care about? How is this currently handled anyway, esp in production? Has the schema changed so little that there was no need for this?

**Comment by WMDE-Fisch** [comment]
Until now the changes introduced to the schema were little enough. In most case we just added a new column somewhere. We did that manually as far as I can recall. 

When adding new functionality we always thought how it would affect the schema and took care, that the changes are simple or trivial. 

Migration is an other topic. I am not sure if the schema tool updater can handle something like that. Doctrine has a migration class. I will read the docs and maybe we should talk about the topic in a meeting.

**Comment by WMDE-Fisch** [comment]
We decided that using the doctrine updater tool is sufficient to address our needs in the near future. As mentioned above the changes to the schema are mostly small and trivial. And we don't want to invest more time in this topic when not needed.

see as well https://phabricator.wikimedia.org/T107273

**Comment by JeroenDeDauw** [comment]
Does that mean we do not need the Updater at all?

**Comment by WMDE-Fisch** [comment]
Hmm atm it looks like it to me ... any opinions @KaiNissen @wmde-manicki ?

**Comment by wmde-manicki** [comment]
I don't have a strong opinion about it but if I am not mistaken is the current Updater class doing only the stuff that is also possible using this cli tool, right? In this case the Updater class, at least as it is now, is rather redundant.
I think it might be required at some point to do some kind of more tricky data migration, i.e. if it is decided to significantly change the current table structure. But there are no particular plans about that kind change afaik. And this kind of thing would also rather require a dedicated tool/classes than the generic Updater class.

**Comment by JeroenDeDauw** [comment]
Ugh... ok, submitted a removal PR: #19
