### ISSUE TITLE
MembershipApplication field questions

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/FundraisingStore#75]
- What is `$company`? I understand that a Donation can be made by a company, though presumably you need an actual person for memberships?
- What is `$name`? Is this some combination of the applicants first name, last name, title and salutation?
- Is `$address`, `$postcode` and `$city`, `$country` the address of the applicant, or is it the billing address?
- What is `$wikimediumShipping`? Do we need to care about this in the frontend application? (I have some sense of deja-vu when asking this, though cannot find where I would have done this before.)
- What are `$comment`, `$wikilogin` and `$tracking`?

**Comment by manicki** [comment]
I'll try to answer with what I remember. But I have a strong feeling that we really need @KaiNissen here:

> What is $name? Is this some combination of the applicants first name, last name, title and salutation?

Isn't it meant to be a combination of the applicant's first and last name same as with the thing called `$data[name]` in the Donation entity? That would be my guess, but it kind of looks like it is always empty for MembershipApplications. Wait, am I having a right feeling this has been discussed quite recently?

> Is $address, $postcode and $city, $country the address of the applicant, or is it the billing address?

I'd say those are for address data of the applicant but it isn't currently assumed that this data is also always a billing address for membership payment(s)?

> What is $wikimediumShipping? Do we need to care about this in the frontend application? 

I'd glad to hear an explanation too. Allowed values seem to be `none`, `mail`, `email` with `none` being set by the current frontend application if some evil GET parameters are not present. I am starting to have a feeling this thing is no longer used? At least production DB records haven't got anything else than `none` since 2014.

> What are $comment, $wikilogin and $tracking?

`$tracking` is a string like "campaign/keyword", used in analysis (but set by frontend app). Similar thing to Donations $data['tracking'].
`$wikilogin` is a "boolean" flag saying if the applicant has been logged-in in her Wikipedia (or whatever else Wiki) when she clicked the banner. But I am not sure if this is still used actually.
`$comment` might be something supposed to be something similar to the Donation's comment (the comment added after sending the membership application) but again I am not sure if this is still used.

**Comment by JeroenDeDauw** [comment]
Thanks for that info already.

> Wait, am I having a right feeling this has been discussed quite recently?

A good way to avoid people repeatedly running into such things is to encode the gained knowledge into the code.

**Comment by KaiNissen** [comment]
> I'll try to answer with what I remember. But I have a strong feeling that we really need @KaiNissen here:

>> What is $name? Is this some combination of the applicants first name, last name, title and salutation?

> Isn't it meant to be a combination of the applicant's first and last name same as with the thing called `$data[name]` in the Donation entity? That would be my guess, but it kind of looks like it is always empty for MembershipApplications. Wait, am I having a right feeling this has been discussed quite recently?

Yes, looks like it's not being used.

>> Is $address, $postcode and $city, $country the address of the applicant, or is it the billing address?

> I'd say those are for address data of the applicant but it isn't currently assumed that this data is also always a billing address for membership payment(s)?

We only collect one address, so this actually is the billing address.

>> What is $wikimediumShipping? Do we need to care about this in the frontend application? 

> I'd glad to hear an explanation too. Allowed values seem to be `none`, `mail`, `email` with `none` being set by the current frontend application if some evil GET parameters are not present. I am starting to have a feeling this thing is no longer used? At least production DB records haven't got anything else than `none` since 2014.

We once had this "newspaper" which was published in print and PDF. This determined which a member wants to subscribe to.

>> What are $comment, $wikilogin and $tracking?

> `$tracking` is a string like "campaign/keyword", used in analysis (but set by frontend app). Similar thing to Donations $data['tracking'].

@manicki is right.

> `$wikilogin` is a "boolean" flag saying if the applicant has been logged-in in her Wikipedia (or whatever else Wiki) when she clicked the banner. But I am not sure if this is still used actually.

Again @manicki is right.This is the third or even fourth campaign in which we don't display banners to logged in users, so I guess we're fine with saying it's not used anymore.

> `$comment` might be something supposed to be something similar to the Donation's comment (the comment added after sending the membership application) but again I am not sure if this is still used.

No, there is currently no way to add a comment to a membership application.

**Comment by JeroenDeDauw** [comment]
> Yes, looks like it's not being used.

https://github.com/wmde/FundraisingStore/pull/76

> We only collect one address, so this actually is the billing address.

Do you think the things should be called `$applicantPostalCode` or `$paymentPostalCode`?

> We once had this "newspaper" which was published in print and PDF. This determined which a member wants to subscribe to.

Does this mean we can kill the field from the db? If not, we need another way to mark this in a way it avoids wasting time in the future.

>> $tracking is a string like "campaign/keyword", used in analysis (but set by frontend app). Similar thing to Donations $data['tracking'].
> @manicki is right.

What is a good name for this then? Anything more specific or otherwise better than `$trackingString`?

> Again @manicki is right.This is the third or even fourth campaign in which we don't display banners to logged in users, so I guess we're fine with saying it's not used anymore.

Same question: can we kill `$wikilogin` from the db then?

> No, there is currently no way to add a comment to a membership application.

Well, what is `$comment` then?

**Comment by JeroenDeDauw** [comment]
Ping pong

**Comment by KaiNissen** [comment]
>> We only collect one address, so this actually is the billing address.

> Do you think the things should be called `$applicantPostalCode` or `$paymentPostalCode`?

`$applicantPostalCode`

>> We once had this "newspaper" which was published in print and PDF. This determined which a member wants to subscribe to.

> Does this mean we can kill the field from the db? If not, we need another way to mark this in a way it avoids wasting time in the future.

As it's highly unlikely that we will ever publish something like this, we can kill it.

>>> $tracking is a string like "campaign/keyword", used in analysis (but set by frontend app). Similar thing to Donations $data['tracking'].
>> @manicki is right.

> What is a good name for this then? Anything more specific or otherwise better than `$trackingString`?

Maybe `$trackingCodes`, or `$campaignCode`?

>> Again @manicki is right.This is the third or even fourth campaign in which we don't display banners to logged in users, so I guess we're fine with saying it's not used anymore.

> Same question: can we kill `$wikilogin` from the db then?

Same answer: Highly unlikely that we will show banners to logged in users, so let's kill it.

>> No, there is currently no way to add a comment to a membership application.

> Well, what is `$comment` then?

Err, rubbish? Let's also kill it. KILL ALL THE THINGS!!! (#80)

**Comment by JeroenDeDauw** [comment]
> Maybe $trackingCodes, or $campaignCode?

Is it accurate to say this field contains "tracking campaign codes"?
